---
# Source: oai-gnb/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gnb-c-ran-role
  namespace: c-ran
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
# Source: oai-gnb/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gnb-c-ran-binding
  namespace: c-ran
subjects:
- kind: ServiceAccount
  name: gnb-sa
  namespace: c-ran
roleRef:
  kind: Role
  name: gnb-c-ran-role
  apiGroup: rbac.authorization.k8s.io
